language: php

matrix:
  fast_finish: true
  include:
    - php: 7.1
    - env: COMPOSER_FLAGS="--prefer-lowest"
      php: 7.1
    - php: 7.2
    - php: 8.0
      dist: bionic

before_install:
  - composer self-update

install:
  - composer update --prefer-source -o $COMPOSER_FLAGS

script:
  - ./vendor/bin/phpunit -c phpunit.xml.dist --coverage-clover=coverage.clover

after_success:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover

cache:
  directories:
    - vendor
    - $HOME/.composer/cache
