<?php

/**
 * Test integration of PHPVCR with PHPUnit using annotations.
 */
class Util_Log_VCRTest extends PHPUnit_Framework_TestCase
{
    /**
     * @vcr unittest_annotation_test
     */
    public function testInterceptsWithAnnotations()
    {
        // Content of tests/fixtures/unittest_annotation_test: "This is a annotation test dummy".
        $result = file_get_contents('http://google.com');
        $this->assertEquals('This is a annotation test dummy.', $result, 'Call was not intercepted (using annotations).');
    }

    /**
     * @vcr unittest_annotation_test.yml
     */
    public function testInterceptsWithAnnotationsAndFileExtension()
    {
        $result = file_get_contents('http://google.com');
        $this->assertEquals('This is a annotation test dummy.', $result, 'Call was not intercepted (using annotations).');
    }

    /**
     * @vcr unittest_annotation_test_auto_generated.yml
     */
    public function testInterceptsWithAnnotationsAutoGenerated()
    {
        file_get_contents('http://google.com');

        $cassettePath = __DIR__ . '/../../../fixtures/unittest_annotation_test_auto_generated.yml';

        $this->assertTrue(
            file_exists($cassettePath),
            'Couldn\'t find the create file by vcr. Tried path: ' . $cassettePath
        );

        $this->assertTrue(
            is_writable($cassettePath),
            'File was found but is not writable: ' . $cassettePath
        );

        $this->assertGreaterThan(
            1,
            filesize($cassettePath),
            'Files doesn\'t have contents: ' . $cassettePath
        );
    }
}
